feat: GET/POST requests logic and tests were added
tarasovEgor/java-filmorate pull request #4
Opened 2023-07-06 21:21 UTC by tarasovEgor

Создан каркас проекта Filmorate, добавлены контроллеры для обработки GET/POST/PUT запросов и соответствующие JUnit-тесты.

2023-07-08 09:37 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            if (film.getName().isEmpty()) {
Код с проверкой повторяется несколько раз, поэтому его нужно вынести в отдельный метод. Дублирования нужно избегать всегда.

2023-07-08 09:39 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public Film createFilm(@Valid @RequestBody Film film) {
Отлично что ичпользуешь @Valid

2023-07-08 09:42 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@Builder(toBuilder = true)
@Builder

2023-07-08 09:46 UTC, VadimZharkov requested changes
Две вещи над которыми нужно поработать 
1 Убрать дублирование кода при проверках, сделать отдельный метод
2 У обоих контроллеров одинаковые методы по созданию и получению сущьностей и  одинаковая логика хранения в мапах, поэтому можно сделать базовый контроллер, куда и вынести все общее.

2023-07-08 20:17 UTC, tarasovEgor commented
Привет, логику контроллеров объединил в MainController, переименовал их в FilmValidationController и UserValidationController, добавил туда все соответствующие методы для валидации.

2023-07-09 07:31 UTC, VadimZharkov approved these changes

2023-07-09 18:30 UTC, merged