Project-10: Friends and Likes added
tarasovEgor/java-filmorate pull request #5
Opened 2023-07-22 19:45 UTC by tarasovEgor

2023-07-24 07:07 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    Optional<Film> getFilmById(Long id, Logger log);
Логгер из параметров лучше убрать, потому что он не является обязательным для работы хранилища. Это просто детали реализации хранилищ. В какой-то реализации хранилища мы будем логгировать, а в какой-то не захотим этого делать.

2023-07-24 07:22 UTC, VadimZharkov requested changes
Перемудрил с контроллерами)
Общая схема такая Контроллер->Сервис->Хранилище.
Контроллер это внешнее API. В класс контроллера группируем все эндпоинты для сущностей одного типа. Контроллер общается с сервисом или несколькими сервисами. В сервисах некая бизнес логика - проверки и т.д.
В хранилище только то что нужно для хранение.
Т.к. у нас две группы эндпоинтов, film и users то предлагаю сделать только два контроллера.
А вот сервисов можно несколько сделать, можно один сервис на контроллер, а можно и разбить на несколько.

2023-07-24 13:24 UTC, tarasovEgor commented
Привет.

2023-07-24 13:37 UTC, tarasovEgor commented
Привет!
Добавил два контроллера для Film и User, в них объединил эндпоинты из Main и эндпоинты для бизнес-логики из сервисов, логгер убрал. Хотелось бы еще получить обратную связь по коду. Хорошо ли он структурирован? Насколько эффективен? Легко ли его читать и что можно изменить? Было бы очень интересно узнать, заранее спасибо)

2023-07-25 08:43 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private InMemoryFilmStorage inMemoryFilmStorage;
попробуй убрать из контроллера inMemoryFilmStorage чтобы контроллер работал только через сервис.
в сервис можно добавить getAllFilms(); и т..д.
смысл в том чтобы разделить проект на слои и каждый слой работает только со своим слоем или низлежащим.
контроллер работает только с сервисами, сервисы с хранилищами и другими сервисами. такая принята архитектура в спринг проектах.

2023-07-25 08:45 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    private InMemoryUserStorage inMemoryUserStorage;
тоже самое попробуй убрать зависимость контроллера от хранилища.

2023-07-25 08:51 UTC, VadimZharkov commented
> 
Про структуризацию и улучшение отписался в комментах. 
Про эффективность пока рано говорить, т.к. пока обычное задание. 
Читать код становится все легче и легче) тут явно виден прогресс.

2023-07-25 08:52 UTC, VadimZharkov requested changes
Можно еще улучшить

2023-07-25 12:38 UTC, tarasovEgor commented
Большое спасибо за обратную связь! Мотивация прибавилась)
Хранилища из контроллеров убрал.

2023-08-04 11:18 UTC, merged