Sprint 11: H2 database added
tarasovEgor/java-filmorate pull request #7
Opened 2023-08-14 17:27 UTC by tarasovEgor

2023-08-22 08:36 UTC, VadimZharkov commented on src/main/resources/schema.sql
> +INSERT INTO genres (genre_id, genre_name) VALUES
insert-ы лучше перенести в data.sql
в schema.sql описываем таблицы, а в data.sql заполняем справочники и/или тестовые данные

2023-08-22 08:51 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +                    .mpa(new MPA(filmRow.getInt("mpa"),
Здесь будет второй запрос к БД, но можно сделать первый select с join и получить нужные данные за один запрос к БД.
Лучше избегать лишних запросов, т.к. нагруженные БД этого не "любят")

2023-08-22 08:59 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +        for (Film f : this.getAllFilms()) {
Не нужно делать такой проверки, т.к. это доп запрос к БД.
Ничего страшного не случится если мы выполним запрос с id которого нет в базе, jdbcTemplate.update вернет кол-во обработанных строк 0, можно на это кинуть эксепшн

2023-08-22 09:04 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +    public TreeSet<Genre> addGenreToFilmObject(Long filmId) {
имя метода говорит о том что будет добавление, а в методе только select, т.е. только получение данных?

2023-08-22 09:20 UTC, VadimZharkov requested changes
Можно оптимизировать запросы, сократив где возможно их количество использую Join.

2023-08-22 19:20 UTC, tarasovEgor commented
Привет, ненужные запросы убрал, проверку на несуществующий id переделал

2023-08-23 05:45 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDAO.java
> +    Optional<Genre> getGenreById(Integer id);
Очень хорошо, что используешь Optional для возврата единичного значения в Dao. В Optional больше смысловой нагрузки чем возвращать просто null если не найдено.

2023-08-23 05:48 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +        return Film.builder()
Хорошо что пользуешься паттерном builder, удобней чем конструктор с множеством параметров.

2023-08-23 05:52 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +        String sqlQuery = "SELECT f.id," +
Для общего развития в 17 джаве появилась фича - техтовые блоки, удобней работать многострочным текстом.
https://javarush.com/groups/posts/3976-kofe-breyk-178-kratkoe-vvedenie-v-java-text-block-kak-preobrazovatjh-list-v-set

2023-08-23 05:54 UTC, VadimZharkov approved these changes

2023-08-27 12:56 UTC, merged